// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvbpUUxLSPCeVDzigw2mVxldBgR_8Fxuk',
    appId: '1:710460581215:web:7908170fc612e130ec42ea',
    messagingSenderId: '710460581215',
    projectId: 'rentapp-ba301',
    authDomain: 'rentapp-ba301.firebaseapp.com',
    storageBucket: 'rentapp-ba301.firebasestorage.app',
    measurementId: 'G-0RQ833JXK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ODNF29bH-iFb6fpyW_jZO10vYrSnaR0',
    appId: '1:710460581215:android:c8f6e8915d582c22ec42ea',
    messagingSenderId: '710460581215',
    projectId: 'rentapp-ba301',
    storageBucket: 'rentapp-ba301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQAL41Wubr0D6oA9lCoq1mKTJgB0XTnGA',
    appId: '1:710460581215:ios:ae438be023ac0a9aec42ea',
    messagingSenderId: '710460581215',
    projectId: 'rentapp-ba301',
    storageBucket: 'rentapp-ba301.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQAL41Wubr0D6oA9lCoq1mKTJgB0XTnGA',
    appId: '1:710460581215:ios:ae438be023ac0a9aec42ea',
    messagingSenderId: '710460581215',
    projectId: 'rentapp-ba301',
    storageBucket: 'rentapp-ba301.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvbpUUxLSPCeVDzigw2mVxldBgR_8Fxuk',
    appId: '1:710460581215:web:93d2a77a1d65b8edec42ea',
    messagingSenderId: '710460581215',
    projectId: 'rentapp-ba301',
    authDomain: 'rentapp-ba301.firebaseapp.com',
    storageBucket: 'rentapp-ba301.firebasestorage.app',
    measurementId: 'G-DHNKVE9H34',
  );
}
